### ISSUE TITLE
batchdeobfuscator pull appears twice in the script

### ISSUE THREAD

**Issue by jxb5151** [CybercentreCanada/assemblyline-development-setup#11]
The git commands for pulling assemblyline-service-batchdeobfuscator.git appear twice within the setup script. This caused a fatal error for me when installing in a WSL environment. 

https://github.com/CybercentreCanada/assemblyline-development-setup/blob/4f0bc02447842aad146c8e042fa90c5645e6055c/setup_vscode.sh#L271

https://github.com/CybercentreCanada/assemblyline-development-setup/blob/4f0bc02447842aad146c8e042fa90c5645e6055c/setup_vscode.sh#L279

Removing the duplication allowed the script to run through successfully, just FYSA.

**Comment by gdesmar** [comment]
Thank you for the report! :)
